---
title: "ClinReport R package"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "90%"
)
```

The aim of ClinReport is to give to R users the possibility to create nice statistical reporting outputs (tables and graphics) in 'Microsoft Word'. 

## Installation

You can install the released version of ClinReport from [CRAN](https://CRAN.R-project.org) with:

```r
install.packages("ClinReport")
```


## Basic example code

```{r, include=T}

library(ClinReport)
library(officer)
library(flextable)

# Load data

data(data)

# Descriptive statistice (Numerical response and 2 explicative variables):

tab1=report.quanti(data=data,y="y_numeric",
		x1="GROUP",x2="TIMEPOINT",at.row="TIMEPOINT",subjid="SUBJID")
tab1

# You can have the correspnding graphic:

gg=plot(tab1,title="Mean response evolution as a function of time by treatment group",
 legend.label="Treatment groups",ylab="Y mean")
gg

```

# Put the results in a docx document  with officer  


```r

doc=read_docx()
doc=report.doc(tab1,title="Example of quantitative descriptive table",doc=doc) 

# See the results

file=paste(tempfile(),".docx",sep="")
print(doc, target =file)

#shell.exec(file)

```


